### ISSUE TITLE
Billboard not installing, even though pop-up says it was installed.

### ISSUE THREAD

**Issue by strudelmedia** [dougblackjr/billboard#1]
I tryied installing this on an EE 5.4.0 site, but it doesn't seem to be installing. I get the EE pop-up window saying that it’s been installed, but it remains greyed out with the “install” button in the Add-Ons listing. I downloaded and tried to install from the zip file. See images below:

It says it was installed:
![successful-install](https://user-images.githubusercontent.com/9244121/109042524-4afdf600-769e-11eb-9bc4-70f9162a0712.png)

But it doesn't look installed here:
![not-installed](https://user-images.githubusercontent.com/9244121/109042589-610bb680-769e-11eb-821f-297ff67f0bd8.png)

**Comment by dougblackjr** [comment]
@strudelmedia Can you tell me if persists to uninstall and reinstall? And do you see it in the types of fields you can create?

**Comment by strudelmedia** [comment]
It does persist with uninstall and reinstall, but the good news is that it seems to be working anyway!

It shows up in the Field list, and I was able to successfully add it and use it, so that’s good. Strange!

Thanks for following up.

> On Feb 24, 2021, at 1:00 PM, Doug Black <notifications@github.com> wrote:
> 
> 
> @strudelmedia Can you tell me if persists to uninstall and reinstall? And do you see it in the types of fields you can create?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 




Edward

…………………………………………
edward ratliff / strudelmedia design
strudelmediadesign.com
tel 646 666 9595

++want to send me a file?
go to wetransfer.com and send to this address

**Comment by dougblackjr** [comment]
@strudelmedia This should be resolved in the latest commit.
